-- MySQL Script generated by MySQL Workbench
-- Tue Nov 29 09:39:14 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema miportfolio
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `miportfolio` ;

-- -----------------------------------------------------
-- Schema miportfolio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `miportfolio` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `miportfolio` ;

-- -----------------------------------------------------
-- Table `miportfolio`.`domicilio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `miportfolio`.`domicilio` ;

CREATE TABLE IF NOT EXISTS `miportfolio`.`domicilio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `direccion` VARCHAR(255) NULL DEFAULT NULL,
  `numero` VARCHAR(255) NULL DEFAULT NULL,
  `provincia` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `miportfolio`.`educacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `miportfolio`.`educacion` ;

CREATE TABLE IF NOT EXISTS `miportfolio`.`educacion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `carrera` VARCHAR(255) NULL DEFAULT NULL,
  `establecimiento` VARCHAR(255) NULL DEFAULT NULL,
  `fin` VARCHAR(255) NULL DEFAULT NULL,
  `inicio` VARCHAR(255) NULL DEFAULT NULL,
  `logo` LONGBLOB NULL DEFAULT NULL,
  `puntaje` DOUBLE NOT NULL,
  `titulo` VARCHAR(255) NULL DEFAULT NULL,
  `persona_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK8co4tldnpfbl6l8oc06veg4jr` (`persona_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `miportfolio`.`experiencia_laboral`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `miportfolio`.`experiencia_laboral` ;

CREATE TABLE IF NOT EXISTS `miportfolio`.`experiencia_laboral` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NULL DEFAULT NULL,
  `fecha_fin` VARCHAR(255) NULL DEFAULT NULL,
  `fecha_inicio` VARCHAR(255) NULL DEFAULT NULL,
  `logo` LONGBLOB NULL DEFAULT NULL,
  `nombre_empresa` VARCHAR(255) NULL DEFAULT NULL,
  `puesto` VARCHAR(255) NULL DEFAULT NULL,
  `persona_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKelaxbjobcjlgfl485oi1wqscv` (`persona_id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `miportfolio`.`persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `miportfolio`.`persona` ;

CREATE TABLE IF NOT EXISTS `miportfolio`.`persona` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `apellido` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `fecha_nacimiento` VARCHAR(255) NULL DEFAULT NULL,
  `foto_perfil` LONGBLOB NULL DEFAULT NULL,
  `foto_portada` LONGBLOB NULL DEFAULT NULL,
  `nacionalidad` VARCHAR(255) NULL DEFAULT NULL,
  `nombre` VARCHAR(255) NULL DEFAULT NULL,
  `ocupacion` VARCHAR(255) NULL DEFAULT NULL,
  `sobre_mi` VARCHAR(255) NULL DEFAULT NULL,
  `id_domicilio` INT NULL DEFAULT NULL,
  `telefono` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKk7mhrlqj0vul6eopsww3wbh5f` (`id_domicilio` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `miportfolio`.`proyecto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `miportfolio`.`proyecto` ;

CREATE TABLE IF NOT EXISTS `miportfolio`.`proyecto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NULL DEFAULT NULL,
  `fecha` VARCHAR(255) NULL DEFAULT NULL,
  `link` VARCHAR(255) NULL DEFAULT NULL,
  `nombre` VARCHAR(255) NULL DEFAULT NULL,
  `persona_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKh9q3ib0v2a6x56ch8dbcw40by` (`persona_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `miportfolio`.`rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `miportfolio`.`rol` ;

CREATE TABLE IF NOT EXISTS `miportfolio`.`rol` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rol_nombre` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `miportfolio`.`skill`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `miportfolio`.`skill` ;

CREATE TABLE IF NOT EXISTS `miportfolio`.`skill` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL DEFAULT NULL,
  `porcentaje` DOUBLE NOT NULL,
  `persona_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKq5lt52vexik5gkhcy4v6r03eb` (`persona_id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `miportfolio`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `miportfolio`.`usuario` ;

CREATE TABLE IF NOT EXISTS `miportfolio`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre_usuario` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `id_persona` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_puhr3k3l7bj71hb7hk7ktpxn0` (`nombre_usuario` ASC) VISIBLE,
  INDEX `FKagix3q8yqktlyj3yp1sn0mcd9` (`id_persona` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `miportfolio`.`usuario_rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `miportfolio`.`usuario_rol` ;

CREATE TABLE IF NOT EXISTS `miportfolio`.`usuario_rol` (
  `usuario_id` INT NOT NULL,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`usuario_id`, `role_id`),
  INDEX `FKne7wo0k7eqbjquw5dxth7wo8i` (`role_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
